version: "3"
services:
  storageserver:
    image: kckusal/dfs:storageserver
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "18861-18863:18861-18863"
  nameserver:
    image: kckusal/dfs:nameserver
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "18860:18860"
  client:
    image: kckusal/dfs:client
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "18859:18859"
  
